### ISSUE TITLE
No Update since one year?

### ISSUE THREAD

**Issue by guettli** [mohawk2/pytest-bdd-web#1]
There was no update since one year...

Why did you stop? What was your finding. Please share what you learned.

**Comment by mohawk2** [comment]
Apart from maybe a couple more examples in the doc, are you saying you think there are things missing in this library? If there aren't, why would it need changes?

**Comment by mohawk2** [comment]
My finding was the library works great. If you have material issues to raise, please do so :-) Closing until then.
